### PR TITLE
Scotland

### PR DESCRIPTION
**Pull request by NadaKartouch**
First draft of changes: 
-- add props to Lesson 1 and remove it from lesson 2 (syllabus will still go through props in lesson 2)
-- remove functional components from lesson 1 and 2 and include them in the homework. 
-- did not remove JSX section as we agreed because i felt that student should know about it and how to include javascript in jsx maybe in the lesson note we need to mention to give it a light touch rather than in depth cover.

### CODE REVIEW

**Comment by NateWr** [comment]
:+1: Should I try to find a mentor to review the module at this stage?

**Comment by alismith-dev** [comment]
Hi! Thanks for the contribution! I haven't had a chance look at this in depth but I wrote the original React module. I'm happy to have a look if you would like.

I'm not sure if the `master` branch has different from the `scotland` branch, but I have been updating `master` as I teach it (in London) so you might want to have a look at that to compare. I'm also currently working on some more improvements in this PR: https://github.com/CodeYourFuture/syllabus/pull/260. This was mostly driven by us in London switching the order of modules so that React comes earlier in the course (i.e. before Node/DB), but I believe you guys in Scotland were already doing that.

**Comment by NadaKartouch** [comment]
Hi guys thanks for the comments 
@Nate still lesson 3 to be revised hopefully this week should be done with node module
@Alaisdair i will deffo have a look at your pull request tonight. Scotland do differ a bit from master (london) but i don't think there are major differences so we can benifit from your changes for sure:)

**Comment by llh1** [comment]
I think the example about React Components could be changed. I understand we want to keep it simple at this stage, but the example of HelloWorld with a component Greeting and a component Mentor is a bit of an anti pattern in React, where we usually do not split and compose components from this standpoint (normally the mentor name would be passed as a prop of Greeting, instead of being a new component). I think we can find a better example closer to the reality of using React, something like this for example: https://reactjs.org/docs/components-and-props.html#composing-components, which illustrate that a component can also be reused several times.

**Comment by llh1** [comment]
Few other comments:
- Embedding JS into JSX: we can remove the mention to Handlebars, as we probably wouldn't have introduced Handlebars before this lesson. 
- Embedding JS into JSX: should we add a note with the "key" props somewhere when we use map() as it's a good practice with React when looping over an array of items and it may confuse students to see warning about it in the console if we omit it.

**Comment by alismith-dev** [comment]
Hey @NadaKartouch @llh1 Not sure if you're still progressing this PR, but just to let you know I've just merged https://github.com/CodeYourFuture/syllabus/pull/260 to the `master` branch. It has some improvements based on running the React module for London class 4 and changes after we switched up the order of modules in London (which I think should now match Glasgow's syllabus more closely I believe).

**Comment by llh1** [comment]
Thanks @40thieves. We are still working on the React module so I'll have a look at the master branch as well :)

**Pull request closed without merging**
